export const PROVIDER_TOKENS = {
  DOSEN_REPOSITORY: 'DOSEN_REPOSITORY',
  MAHASISWA_REPOSITORY: 'MAHASISWA_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
  CACHE_PORT: 'CACHE_PORT',
  HASHER_PORT: 'HASHER_PORT',
} as const;
